#pragma once

#include <QtCore/qglobal.h>

#if defined(SIMPLETRAININGLOGLIB_LIBRARY)
#  define SIMPLETRAININGLOGLIB_EXPORT Q_DECL_EXPORT
#else
#  define SIMPLETRAININGLOGLIB_EXPORT Q_DECL_IMPORT
#endif
